# -*- coding: utf-8 -*-
"""week4-A108060116-黃旖萱.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0tb9l5Cpez3D8BcihKyNaJuJe19ozFN
"""

print("hello world")

print(1+1)

print("A108060044林恩")